name: Web Build

on:
  push:
    branches: [ '*' ]
    paths:
      - 'adnmb-backup-web/**'
      - '.github/workflows/web.yml'
  pull_request:
    branches: [ '*' ]
    paths:
      - 'adnmb-backup-web/**'
      - '.github/workflows/web.yml'
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build:
    strategy:
      matrix:
        include:
          - os: windows-latest
            platform: win
            arch: x64
            ext: .exe
          - os: ubuntu-latest
            platform: linux
            arch: x64
          - os: ubuntu-22.04-arm
            platform: linux
            arch: arm64
          - os: macos-latest
            platform: macos
            arch: arm64

    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "20"

      - uses: pnpm/action-setup@v4
        with:
          version: 9

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Check Project
        run: pnpm check

      - name: Build project
        run: pnpm build

